---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
cds:
  drafts.enforce-readonly: true
  security.mock.users:
    admin:
      roles:
      - admin
  data-source.csv.paths:
  - "db/data/**"
  - "../db/data/**"
  - "target/cds/**"
  - "../target/cds/**"
  - "node_modules/@capire/**"
  - "../node_modules/@capire/**"
  - "../../node_modules/@capire/**"
---
spring:
  config.activate.on-profile: "cloud"
cds:
  security.mock.enabled: false # required due to AMS lib
  remote.services:
    xflights:
      type: hcql
      model: sap.capire.flights.data
      http:
        suffix: /hcql
      binding:
        name: xtravels-ias
        onBehalfOf: systemUser
        options:
          url: ${XFLIGHTS_URL} # from mta.yaml
          ias-dependency-name: data-consumer
---
spring:
  config.activate.on-profile: hybrid
cds:
  remote.services:
    xflights:
      type: hcql
      model: sap.capire.flights.data
      destination:
        properties:
          url: http://localhost:8081/hcql
          User: consumer
          Password:
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  data-source.auto-config.enabled: false
